import type { Metadata } from "next";
import SessionProvider from "@/components/SessionProvider";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "E-commerce platform",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}